# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(969, 564)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.qtBBrowse = QtGui.QPushButton(Dialog)
        self.qtBBrowse.setObjectName(_fromUtf8("qtBBrowse"))
        self.gridLayout_2.addWidget(self.qtBBrowse, 1, 1, 1, 1)
        self.qtBrowse = QtGui.QLineEdit(Dialog)
        self.qtBrowse.setObjectName(_fromUtf8("qtBrowse"))
        self.gridLayout_2.addWidget(self.qtBrowse, 1, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.qtLGraph = QtGui.QLabel(Dialog)
        self.qtLGraph.setObjectName(_fromUtf8("qtLGraph"))
        self.verticalLayout_2.addWidget(self.qtLGraph)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2.addWidget(self.widget)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.qtCRawData = QtGui.QCheckBox(Dialog)
        self.qtCRawData.setObjectName(_fromUtf8("qtCRawData"))
        self.verticalLayout_3.addWidget(self.qtCRawData)
        self.qtCBias = QtGui.QCheckBox(Dialog)
        self.qtCBias.setObjectName(_fromUtf8("qtCBias"))
        self.verticalLayout_3.addWidget(self.qtCBias)
        self.qtCSF = QtGui.QCheckBox(Dialog)
        self.qtCSF.setObjectName(_fromUtf8("qtCSF"))
        self.verticalLayout_3.addWidget(self.qtCSF)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.qtGBiasSF = QtGui.QGridLayout()
        self.qtGBiasSF.setObjectName(_fromUtf8("qtGBiasSF"))
        self.qtSSFX = QtGui.QDoubleSpinBox(Dialog)
        self.qtSSFX.setDecimals(4)
        self.qtSSFX.setMinimum(0.0001)
        self.qtSSFX.setProperty("value", 1.0)
        self.qtSSFX.setObjectName(_fromUtf8("qtSSFX"))
        self.qtGBiasSF.addWidget(self.qtSSFX, 6, 0, 1, 1)
        self.qtLSFZ = QtGui.QLabel(Dialog)
        self.qtLSFZ.setObjectName(_fromUtf8("qtLSFZ"))
        self.qtGBiasSF.addWidget(self.qtLSFZ, 5, 2, 1, 1)
        self.qtSBiasZ = QtGui.QDoubleSpinBox(Dialog)
        self.qtSBiasZ.setDecimals(4)
        self.qtSBiasZ.setMinimum(-99.99)
        self.qtSBiasZ.setSingleStep(0.01)
        self.qtSBiasZ.setObjectName(_fromUtf8("qtSBiasZ"))
        self.qtGBiasSF.addWidget(self.qtSBiasZ, 4, 2, 1, 1)
        self.qtSBiasX = QtGui.QDoubleSpinBox(Dialog)
        self.qtSBiasX.setDecimals(4)
        self.qtSBiasX.setMinimum(-99.99)
        self.qtSBiasX.setSingleStep(0.01)
        self.qtSBiasX.setObjectName(_fromUtf8("qtSBiasX"))
        self.qtGBiasSF.addWidget(self.qtSBiasX, 4, 0, 1, 1)
        self.qtLSFX = QtGui.QLabel(Dialog)
        self.qtLSFX.setObjectName(_fromUtf8("qtLSFX"))
        self.qtGBiasSF.addWidget(self.qtLSFX, 5, 0, 1, 1)
        self.qtSSFZ = QtGui.QDoubleSpinBox(Dialog)
        self.qtSSFZ.setDecimals(4)
        self.qtSSFZ.setMinimum(0.0001)
        self.qtSSFZ.setProperty("value", 1.0)
        self.qtSSFZ.setObjectName(_fromUtf8("qtSSFZ"))
        self.qtGBiasSF.addWidget(self.qtSSFZ, 6, 2, 1, 1)
        self.qtLBiasY = QtGui.QLabel(Dialog)
        self.qtLBiasY.setObjectName(_fromUtf8("qtLBiasY"))
        self.qtGBiasSF.addWidget(self.qtLBiasY, 3, 1, 1, 1)
        self.qtLSFY = QtGui.QLabel(Dialog)
        self.qtLSFY.setObjectName(_fromUtf8("qtLSFY"))
        self.qtGBiasSF.addWidget(self.qtLSFY, 5, 1, 1, 1)
        self.qtSBiasY = QtGui.QDoubleSpinBox(Dialog)
        self.qtSBiasY.setDecimals(4)
        self.qtSBiasY.setMinimum(-99.99)
        self.qtSBiasY.setSingleStep(0.01)
        self.qtSBiasY.setObjectName(_fromUtf8("qtSBiasY"))
        self.qtGBiasSF.addWidget(self.qtSBiasY, 4, 1, 1, 1)
        self.qtLBiasX = QtGui.QLabel(Dialog)
        self.qtLBiasX.setObjectName(_fromUtf8("qtLBiasX"))
        self.qtGBiasSF.addWidget(self.qtLBiasX, 3, 0, 1, 1)
        self.qtSSFY = QtGui.QDoubleSpinBox(Dialog)
        self.qtSSFY.setDecimals(4)
        self.qtSSFY.setMinimum(0.0001)
        self.qtSSFY.setProperty("value", 1.0)
        self.qtSSFY.setObjectName(_fromUtf8("qtSSFY"))
        self.qtGBiasSF.addWidget(self.qtSSFY, 6, 1, 1, 1)
        self.qtLBiasZ = QtGui.QLabel(Dialog)
        self.qtLBiasZ.setObjectName(_fromUtf8("qtLBiasZ"))
        self.qtGBiasSF.addWidget(self.qtLBiasZ, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(328, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.qtGBiasSF.addItem(spacerItem, 5, 3, 1, 1)
        self.qtSGyroSF = QtGui.QDoubleSpinBox(Dialog)
        self.qtSGyroSF.setDecimals(4)
        self.qtSGyroSF.setMinimum(0.0001)
        self.qtSGyroSF.setMaximum(999.9999)
        self.qtSGyroSF.setProperty("value", 1.0)
        self.qtSGyroSF.setObjectName(_fromUtf8("qtSGyroSF"))
        self.qtGBiasSF.addWidget(self.qtSGyroSF, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.qtGBiasSF.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.qtGBiasSF)
        self.qtVLCom = QtGui.QVBoxLayout()
        self.qtVLCom.setObjectName(_fromUtf8("qtVLCom"))
        self.qtComPortsLabel = QtGui.QLabel(Dialog)
        self.qtComPortsLabel.setObjectName(_fromUtf8("qtComPortsLabel"))
        self.qtVLCom.addWidget(self.qtComPortsLabel)
        self.qtComPorts = QtGui.QComboBox(Dialog)
        self.qtComPorts.setMinimumSize(QtCore.QSize(150, 0))
        self.qtComPorts.setObjectName(_fromUtf8("qtComPorts"))
        self.qtVLCom.addWidget(self.qtComPorts)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.qtVLCom.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.qtVLCom)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.qtBExit = QtGui.QPushButton(Dialog)
        self.qtBExit.setObjectName(_fromUtf8("qtBExit"))
        self.horizontalLayout.addWidget(self.qtBExit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.qtCRecorde = QtGui.QCheckBox(Dialog)
        self.qtCRecorde.setObjectName(_fromUtf8("qtCRecorde"))
        self.horizontalLayout.addWidget(self.qtCRecorde)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.qtBStream = QtGui.QPushButton(Dialog)
        self.qtBStream.setObjectName(_fromUtf8("qtBStream"))
        self.horizontalLayout.addWidget(self.qtBStream)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label.setBuddy(self.qtBrowse)
        self.qtLSFZ.setBuddy(self.qtSSFZ)
        self.qtLSFX.setBuddy(self.qtSSFX)
        self.qtLBiasY.setBuddy(self.qtSBiasY)
        self.qtLSFY.setBuddy(self.qtSSFY)
        self.qtLBiasX.setBuddy(self.qtSBiasX)
        self.qtLBiasZ.setBuddy(self.qtSBiasZ)
        self.label_3.setBuddy(self.qtSGyroSF)
        self.qtComPortsLabel.setBuddy(self.qtComPorts)

        self.retranslateUi(Dialog)
        self.qtComPorts.setCurrentIndex(-1)
        QtCore.QObject.connect(self.qtBExit, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.qtCRawData, self.qtCBias)
        Dialog.setTabOrder(self.qtCBias, self.qtCSF)
        Dialog.setTabOrder(self.qtCSF, self.qtSBiasX)
        Dialog.setTabOrder(self.qtSBiasX, self.qtSBiasY)
        Dialog.setTabOrder(self.qtSBiasY, self.qtSBiasZ)
        Dialog.setTabOrder(self.qtSBiasZ, self.qtSSFX)
        Dialog.setTabOrder(self.qtSSFX, self.qtSSFY)
        Dialog.setTabOrder(self.qtSSFY, self.qtSSFZ)
        Dialog.setTabOrder(self.qtSSFZ, self.qtBrowse)
        Dialog.setTabOrder(self.qtBrowse, self.qtBBrowse)
        Dialog.setTabOrder(self.qtBBrowse, self.qtComPorts)
        Dialog.setTabOrder(self.qtComPorts, self.qtBStream)
        Dialog.setTabOrder(self.qtBStream, self.qtCRecorde)
        Dialog.setTabOrder(self.qtCRecorde, self.qtBExit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Main", None))
        self.qtBBrowse.setText(_translate("Dialog", "...", None))
        self.label.setText(_translate("Dialog", "File location", None))
        self.qtLGraph.setText(_translate("Dialog", "Output", None))
        self.qtCRawData.setText(_translate("Dialog", "Raw data", None))
        self.qtCBias.setText(_translate("Dialog", "Bias", None))
        self.qtCSF.setText(_translate("Dialog", "Scale Factor", None))
        self.qtLSFZ.setText(_translate("Dialog", "Scale Factor Z", None))
        self.qtLSFX.setText(_translate("Dialog", "Scale Factor X", None))
        self.qtLBiasY.setText(_translate("Dialog", "Bias Y [°/sec]", None))
        self.qtLSFY.setText(_translate("Dialog", "Scale Factor Y", None))
        self.qtLBiasX.setText(_translate("Dialog", "Bias X [°/sec]", None))
        self.qtLBiasZ.setText(_translate("Dialog", "Bias Z [°/sec]", None))
        self.label_3.setText(_translate("Dialog", "Manufacture SF\n"
"[raw/°/sec]", None))
        self.qtComPortsLabel.setText(_translate("Dialog", "Com", None))
        self.qtBExit.setText(_translate("Dialog", "Exit", None))
        self.qtCRecorde.setText(_translate("Dialog", "Recorde", None))
        self.qtBStream.setText(_translate("Dialog", "Stream", None))

